[project]
name = "snappcb-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gerbonara>=1.5.0",
    "shapely>=2.1.1",
    "svgwrite>=1.4.3",
]
